### PR TITLE
avr-gcc48: avoid self-references

### PR DESCRIPTION
**Pull request by bfontaine**
I also removed the duplicated `keg_only` clause.

This will probably fix https://github.com/Homebrew/homebrew/issues/44837.

### CODE REVIEW

**Comment by DomT4** [comment]
@ladislas Can you take a look at this please? We keep getting issues about this tap in Homebrew and there's not a lot we can do to fix them ourselves.

**Comment by mralexgray** [comment]
Please fix.

**Comment by mralexgray** [comment]
this DOES fix Homebrew/homebrew#44837, I can confirm.

**Comment by ladislas** [comment]
sorry guys for the long answer, I've been pretty busy with my startup lately. I advise you to take a look at [osx-cross/homebrew-avr](https://github.com/osx-cross/homebrew-avr). It is based partly on my work and is the most up to date version of this formula.

**Pull request merged**
